### ISSUE TITLE
simulate program run failed

### ISSUE THREAD

**Issue by yuxiaoleipeng** [PerfVec/PerfVec#1]
Hi, i can simulate program with Tutorials/mm 8 8 8, but when i use spec17 binary like 500.perlbench, it has error: No SE workload is compatible with %s

**Comment by yuxiaoleipeng** [comment]
i find the reason is the binary i build is x86, But the gem5 version you provide doesn't seem to be able to compile opt for the x86 platforms?

**Comment by lingda-li** [comment]
Sorry for the late response. Yes the current version doesn't support x86 and only supports ARMv8.

**Comment by liuqinfei** [comment]
Ah, I see. Since you're using ./build/ARM/gem5.opt, it can only run binaries compiled for ARM platforms. After trying a binary compiled specifically for ARM, the simulation works smoothly and performs as expected.
